FROM alpine

# ENV http_proxy 'http://192.168.56.1:8123'
# ENV https_proxy 'http://192.168.56.1:8123'

RUN apk add --no-cache \
  bash \
  curl \
  python3 \
  && apk add --no-cache --virtual .build-deps build-base linux-headers musl-dev python3-dev

COPY . /app
RUN chmod 777 /app
WORKDIR /app

RUN pip3 install --no-cache-dir -U -r /app/requirements.txt

RUN apk del .build-deps

RUN adduser -D tomcat
USER tomcat
CMD bash /app/entrypoint.sh
