#!/usr/bin/env bash

#
cat alpine > Dockerfile
echo 'EXPOSE 8080' >> Dockerfile
echo 'ENTRYPOINT /app/entrypoint.sh' >> Dockerfile

#
cat alpine > Dockerfile.heroku
echo 'CMD bash /app/entrypoint.sh' >> Dockerfile.heroku
